#
# Copyright (c) 2023 Risu
#
#  This source code is licensed under the MIT license found in the
#  LICENSE file in the root directory of this source tree.
#
#

---
hammuni:
  api:
    url: ${POINTS_API_URL}
    app: ${BOT_APP_ID}
    username: ${POINTS_API_USERNAME}
    password: ${POINTS_API_PASSWORD}
    detail-prefix: 'hammuni:'
  bot:
    token: ${DISCORD_TOKEN}
    guild: 720363503906717818
    survey-channels: 1054239691785908344, 1059756130760396830
    sharing-channels: 1059769901541228625, 1059770083334950922, 758685434502184990, 750237673226240050, 887232676451483648
    reset:
      time: '00:00'
      cron: '0 0 0 * * *'
      zone: Asia/Tokyo
